### ISSUE TITLE
Rotation Geometry and Structure Viewer does not  work!!!!!

### ISSUE THREAD

**Issue by Liuzhengwang01** [seto77/ReciPro#20]
@seto77 Thanks for your Recipro. It is very useful. It worked properly one month ago, but recently it comes to a trouble, when it is opened, it prompts"error during initializing GLcontrol", "the type initializer for crystallography.OpenGL. GLControlAlpha threw an exception". When I  click on the structure viewer on the user interface, it comes up (3D rendering disable mode), but at this time, I do not check disable OpenGL. looking forward to your help.

**Comment by seto77** [comment]
I'm very sorry for any inconvenience caused.
It is a strange situation because the versions I have released in the last few months have not changed the OpenGL part. Do you have the same OpenGL problem on other PCs?

In the meantime, please check "Option => Reset registry", and restart ReciPro. It may improve the situation.

**Comment by Liuzhengwang01** [comment]
@seto77 on home PC, it is ok!
If reset registry and restart recipro, it doesn't work.

**Comment by seto77** [comment]
It appears to be an environment-dependent problem.
Have you updated your graphics driver recently? A different version of the driver may fix the problem.

**Comment by Liuzhengwang01** [comment]
@seto77 I didn't update the graphics driver before. Today, I try the different version of the quadro P2200 , but it doesn't work. please check the detailed information below:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeInitializationException: The type initializer for 'Crystallography.OpenGL.GLControlAlpha' threw an exception.
 ---> System.Management.ManagementException: 无效类 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Crystallography.OpenGL.GLControlAlpha..cctor()
   --- End of inner exception stack trace ---
   at Crystallography.OpenGL.GLControlAlpha..ctor(FragShaders shaders)
   at ReciPro.FormStructureViewer.FormStructureViewer_Load(Object sender, EventArgs e) in D:\Users\seto\source\repos\ReciPro\ReciPro\StructureViewer\FormStructureViewer.cs:line 134
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.CoreLib.dll
----------------------------------------
ReciPro
    Assembly Version: 2023.5.16.621
    Win32 Version: 2023.5.16.0621
    CodeBase: file:///C:/reciproc/ReciPro.dll
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.dll
----------------------------------------
Crystallography
    Assembly Version: 2023.5.16.621
    Win32 Version: 2023.5.16.0621
    CodeBase: file:///C:/reciproc/Crystallography.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Numerics.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ComponentModel.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/Microsoft.Win32.Registry.dll
----------------------------------------
Crystallography.Controls
    Assembly Version: 2023.5.16.621
    Win32 Version: 2023.5.16.0621
    CodeBase: file:///C:/reciproc/Crystallography.Controls.dll
----------------------------------------
MemoryPack.Core
    Assembly Version: 1.9.13.0
    Win32 Version: 1.9.13.0
    CodeBase: file:///C:/reciproc/MemoryPack.Core.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Memory.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.IO.Compression.dll
----------------------------------------
System.IO.Compression.Brotli
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.IO.Compression.Brotli.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Concurrent.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.ObjectModel.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.Immutable.dll
----------------------------------------
System.Linq
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Linq.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Numerics.Vectors.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.Uri.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Loader.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17501
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.Drawing.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Private.Xml.dll
----------------------------------------
System.Linq.Parallel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Linq.Parallel.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.Tracing.dll
----------------------------------------
System.Data.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Data.Common.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Text.RegularExpressions.dll
----------------------------------------
MathNet.Numerics
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/reciproc/MathNet.Numerics.dll
----------------------------------------
MathNet.Numerics.Providers.MKL
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/reciproc/MathNet.Numerics.Providers.MKL.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Threading.Tasks.Parallel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.Tasks.Parallel.dll
----------------------------------------
Microsoft.Dynamic
    Assembly Version: 1.3.3.0
    Win32 Version: 1.3.3.1000
    CodeBase: file:///C:/reciproc/Microsoft.Dynamic.dll
----------------------------------------
MathNet.Numerics.Providers.OpenBLAS
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0.0
    CodeBase: file:///C:/reciproc/MathNet.Numerics.Providers.OpenBLAS.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.IO.FileSystem.dll
----------------------------------------
SimdLinq
    Assembly Version: 1.3.2.0
    Win32 Version: 1.3.2.0
    CodeBase: file:///C:/reciproc/SimdLinq.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Collections.NonGeneric.dll
----------------------------------------
Crystallography.OpenGL
    Assembly Version: 2023.5.16.621
    Win32 Version: 2023.5.16.0621
    CodeBase: file:///C:/reciproc/Crystallography.OpenGL.dll
----------------------------------------
OpenTK
    Assembly Version: 3.3.3.0
    Win32 Version: 3.3.3
    CodeBase: file:///C:/reciproc/OpenTK.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/mscorlib.dll
----------------------------------------
IronPython
    Assembly Version: 3.4.0.0
    Win32 Version: 3.4.0.1000
    CodeBase: file:///C:/reciproc/IronPython.dll
----------------------------------------
Microsoft.Scripting
    Assembly Version: 1.3.3.0
    Win32 Version: 1.3.3.1000
    CodeBase: file:///C:/reciproc/Microsoft.Scripting.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.3.3.0
    Win32 Version: 3.3.3
    CodeBase: file:///C:/reciproc/OpenTK.GLControl.dll
----------------------------------------
System.Management
    Assembly Version: 7.0.0.1
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/reciproc/runtimes/win/lib/net7.0/System.Management.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.CodeDom
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.5/System.CodeDom.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Linq.Expressions.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Text.Encoding.Extensions.dll
----------------------------------------
IronPython.Modules
    Assembly Version: 3.4.0.0
    Win32 Version: 3.4.0.1000
    CodeBase: file:///C:/reciproc/IronPython.Modules.dll
----------------------------------------
System.Console
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Console.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Threading.ThreadPool.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Emit.dll
----------------------------------------
Snippets.scripting
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.Process.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/Microsoft.CSharp.dll
----------------------------------------
ImagingSolution.Control.GraphicsBox
    Assembly Version: 1.1.1.0
    Win32 Version: 1.1.1.0
    CodeBase: file:///C:/reciproc/ImagingSolution.Control.GraphicsBox.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Xml.XmlSerializer.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Runtime.Intrinsics
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Runtime.Intrinsics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: n/a
    CodeBase: 
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.523.17405
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.5/System.Reflection.Metadata.dll
----------------------------------------

************** JIT Debugging **************
